import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Receipt, PersonTotal } from "./types";

export function exportReceiptPdf(receipt: Receipt, totals: PersonTotal[]) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 16;
  let y = 18;

  // ── Header ──────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(30, 30, 30);
  doc.text("Receipt Split", margin, y);

  const date = new Date(receipt.date).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(140, 140, 140);
  doc.text(date, pageW - margin, y, { align: "right" });
  y += 7;

  if (receipt.storeName) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text(receipt.storeName, margin, y);
    y += 6;
  }

  const grandTotal = totals.reduce((s, t) => s + t.total, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text(`$${grandTotal.toFixed(2)} total`, margin, y);
  y += 10;

  // ── Divider ─────────────────────────────────────────────────────────
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // ── Items table ──────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("ITEMS", margin, y);
  y += 3;

  const itemRows = receipt.items.map((item) => {
    const names = item.assignedTo
      .map((id) => receipt.people.find((p) => p.id === id)?.name ?? id)
      .join(", ");
    return [item.name, `$${item.price.toFixed(2)}`, names || "shared"];
  });

  autoTable(doc, {
    startY: y,
    head: [["Item", "Price", "Assigned to"]],
    body: itemRows,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: { top: 2.5, bottom: 2.5, left: 2, right: 2 },
      textColor: [40, 40, 40],
    },
    headStyles: {
      fillColor: [248, 248, 248],
      textColor: [110, 110, 110],
      fontStyle: "bold",
      fontSize: 8,
      lineColor: [220, 220, 220],
      lineWidth: 0.3,
    },
    bodyStyles: { lineColor: [238, 238, 238], lineWidth: 0.2 },
    columnStyles: { 1: { halign: "right" } },
    theme: "plain",
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 5;

  if (receipt.tax > 0 || receipt.tip > 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    const parts: string[] = [];
    if (receipt.tax > 0) parts.push(`Tax $${receipt.tax.toFixed(2)}`);
    if (receipt.tip > 0) parts.push(`Tip $${receipt.tip.toFixed(2)}`);
    doc.text(`${parts.join(" · ")} — split proportionally`, margin, y);
    y += 9;
  }

  // ── Divider ─────────────────────────────────────────────────────────
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // ── Per-person summary ───────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("WHO OWES WHAT", margin, y);
  y += 3;

  const personRows = totals
    .filter((t) => t.total > 0)
    .map((t) => [
      t.person.name,
      `$${t.subtotal.toFixed(2)}`,
      `$${t.sharedShare.toFixed(2)}`,
      `$${t.total.toFixed(2)}`,
    ]);

  autoTable(doc, {
    startY: y,
    head: [["Person", "Items subtotal", "Tax/tip share", "Total"]],
    body: personRows,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: { top: 2.5, bottom: 2.5, left: 2, right: 2 },
      textColor: [40, 40, 40],
    },
    headStyles: {
      fillColor: [248, 248, 248],
      textColor: [110, 110, 110],
      fontStyle: "bold",
      fontSize: 8,
      lineColor: [220, 220, 220],
      lineWidth: 0.3,
    },
    bodyStyles: { lineColor: [238, 238, 238], lineWidth: 0.2 },
    columnStyles: {
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right", fontStyle: "bold" },
    },
    theme: "plain",
  });

  // ── Footer ───────────────────────────────────────────────────────────
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(190, 190, 190);
  doc.text(
    "generated by receipt-split-alpha.vercel.app",
    pageW / 2,
    pageH - 8,
    { align: "center" }
  );

  // ── Save ─────────────────────────────────────────────────────────────
  const dateStr = new Date(receipt.date).toISOString().split("T")[0];
  const storeSlug = receipt.storeName
    ? `-${receipt.storeName.toLowerCase().replace(/[^a-z0-9]/g, "")}`
    : "";
  doc.save(`receipt-split${storeSlug}-${dateStr}.pdf`);
}
